### ISSUE TITLE
Parse report date from inspection PDFs

### ISSUE THREAD

**Issue by jsvine** [data-liberation-project/aphis-inspection-reports#36]
The *report* date is is a distinct field from the *inspection* date, and can be found at the bottom of each main page:

<img width="949" alt="Screen Shot" src="https://user-images.githubusercontent.com/534702/211404834-9972614b-3ab2-4a93-ab73-2d5f8b8eab07.png">

I've noticed that some reports are dated quite some time after the inspection took place; it'd be interesting to see the distribution and the outliers.

**Comment by gcappaert** [comment]
Starting in on this. I've got a decent handle on pdfplumber (which is great, by the way, I have never found a better PDF parser). I'll have something to pull in the next couple of days here.

For testing (and my own reference), one inspection that has a post-dated report: 2016090000786401.

**Comment by jsvine** [comment]
Thanks for taking this on, @gcappaert! (And thanks for the kind words about `pdfplumber`!)

**Comment by jsvine** [comment]
Completed in #55 🎉
